### PR TITLE
Fix factual inaccuracy

### PR DESCRIPTION
**Pull request by rjc**
`AnonCVS` is **not** part of the base OS.

### CODE REVIEW

**Comment by noqqe** [comment]
You are right, but actually I still like the point that open source code was not the default back in the old days.

**Comment by rjc** [comment]
I do understand what you had in mind, but the reader might not! :^)
The concept of anonymous access to code was pioneered here, but the software itself is *not* part of the base system - that's what I wanted to clarify.

**Comment by noqqe** [comment]
@rjc  do you think the text in its currently deployed version (see my fix commit) is accurate?

Or do we need another change here?

**Comment by rjc** [comment]
Hmm... not sure if it reads well. I'll ponder and will send another PR if need be :^)

**Pull request merged**
