### PR TITLE
Improve Wording

### PR DESCRIPTION
**Pull request by jaywilliams**

### CODE REVIEW

**Comment by hucste** [comment]
Why do you transform the sentence, as-is: 
> FFS2 is the new filesystem by default on nearly all architectures, since OpenBSD 6.7.
No. it's on for all supported architectures! 

And why do you delete: 
> It means *Enhanced Fast Filesystem*.
?

I'm OK, for the rest.

**Comment by jaywilliams** [comment]
I couldn't find any references that FFS2 stands for "Enhanced Fast Filesystem". (Maybe I'm missing something?)

https://man.openbsd.org/man8/mount_ffs.8 calls it "Berkeley Fast File System"

**Comment by hucste** [comment]
See more newfs(8):
https://man.openbsd.org/newfs#O ;-)

Before writing this, I discussed it with Solene@, one OpenBSD member team.

**Comment by noqqe** [comment]
> I couldn't find any references that FFS2 stands for "Enhanced Fast Filesystem". (Maybe I'm missing something?)

Would also leave it in as @hucste described

**Comment by jaywilliams** [comment]
Thanks @hucste for the insight. I've updated the patch, which I hope makes it easier to read.

**Comment by hucste** [comment]
OK, I will merge it!

**Pull request merged**
