### PR TITLE
Added fact about -fwrapv compiler flag and mentioned explicit_bzero(3) idea in README

### PR DESCRIPTION
**Pull request by artsi0m**
I wrote about `-fwrapv` flag in clang and mentioned `explicit_bzero(3)` in README.
I hope there is no typos in my contribution this time.

### CODE REVIEW

**Comment by hucste** [comment]
Hi.
OK for the README, but for the second, change the title and the name of the file by clang. The content is good! 
And add : 
- that clang is the default compilator, on few archs (at the beginning of the file)
- into the sections "details", a link to manpage for clang.

Thanks for your contribution.

**Comment by artsi0m** [comment]
>     * that clang is the default compilator, on few archs (at the beginning of the file)

OK. Should i mention all architectures on which clang is default compiler or just write:
`Clang is the default compiler on a few architectures`  at the beginning of the file ?
Also i should say that i wanted to write just about `-fwrapv` flag in clang, 
not about clang becoming default compiler on certain architectures, because latter is much broader topic 
and i am not sure that i can cover it well, although i understand that having modern compiler is important.

**Comment by artsi0m** [comment]
Also i don't think that claim about `few` architectures is correct today.
See https://github.com/openbsd/src/blob/master/share/mk/bsd.own.mk#L18
So, i'd rather  write `on most architectures`

**Comment by hucste** [comment]
this seems me correct.

**Comment by artsi0m** [comment]
Thanks a lot for reviewing and merging my pull request.

**Comment by hucste** [comment]
Hi.

See this comment on Mastodon: https://bsd.network/@brynet/108512040373473527

**Comment by hucste** [comment]
Hi.

R: 2

**Comment by artsi0m** [comment]
Done.

**Pull request merged**
