### PR TITLE
Add: informations about rpki-client

### PR DESCRIPTION
**Pull request by hucste**
Add:
- first date on 6.7
- website url

@mischapeters: ok?

### CODE REVIEW

**Comment by mischapeters** [comment]
I believe rpki-client was first seen in 6.6, but didn't see a proper confirmation of that.
I tend to link to manual pages, but you can also add a link to the site itself.

**Comment by hucste** [comment]
> I believe rpki-client was first seen in 6.6, but didn't see a proper confirmation of that.

If I'm not wrong, it was on current after 6.6! So, in the release 6.7. 

> I tend to link to manual pages, but you can also add a link to the site itself.

Link to the site in this case seems me normal! :p

**Comment by mischapeters** [comment]
You could be right.
Go for it!

**Comment by mischapeters** [comment]
6.7 it is indeed.

https://www.openbsd.org/67.html
Enabled rpki-client(8), a free, easy-to-use implementation of the Resource Public Key Infrastructure (RPKI) for Relying Parties (RP) to facilitate validation of the Route Origin of a BGP announcement. The program queries the RPKI repository system and outputs Validated ROA Payloads in the configuration format of OpenBGPD, BIRD, and also as CSV or JSON objects for consumption by other routing stacks.

**Pull request merged**
